# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc/proto/groups.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/grpc/proto/groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pp/grpc/proto/groups.proto\x12\x06groups\"O\n\x16\x43heckMembershipRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nscope_type\x18\x02 \x01(\t\x12\x10\n\x08scope_id\x18\x03 \x01(\t\":\n\x17\x43heckMembershipResponse\x12\x11\n\tis_member\x18\x01 \x01(\x08\x12\x0c\n\x04role\x18\x02 \x01(\t\"?\n\x17\x43heckSharedGroupRequest\x12\x11\n\tuser_id_1\x18\x01 \x01(\t\x12\x11\n\tuser_id_2\x18\x02 \x01(\t\"/\n\x18\x43heckSharedGroupResponse\x12\x13\n\x0bshare_group\x18\x01 \x01(\x08\x32\xbf\x01\n\x0eGroupsInternal\x12T\n\x0f\x43heckMembership\x12\x1e.groups.CheckMembershipRequest\x1a\x1f.groups.CheckMembershipResponse\"\x00\x12W\n\x10\x43heckSharedGroup\x12\x1f.groups.CheckSharedGroupRequest\x1a .groups.CheckSharedGroupResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc.proto.groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKMEMBERSHIPREQUEST']._serialized_start=39
  _globals['_CHECKMEMBERSHIPREQUEST']._serialized_end=118
  _globals['_CHECKMEMBERSHIPRESPONSE']._serialized_start=120
  _globals['_CHECKMEMBERSHIPRESPONSE']._serialized_end=178
  _globals['_CHECKSHAREDGROUPREQUEST']._serialized_start=180
  _globals['_CHECKSHAREDGROUPREQUEST']._serialized_end=243
  _globals['_CHECKSHAREDGROUPRESPONSE']._serialized_start=245
  _globals['_CHECKSHAREDGROUPRESPONSE']._serialized_end=292
  _globals['_GROUPSINTERNAL']._serialized_start=295
  _globals['_GROUPSINTERNAL']._serialized_end=486
# @@protoc_insertion_point(module_scope)
