# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc.proto import groups_pb2 as app_dot_grpc_dot_proto_dot_groups__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/grpc/proto/groups_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroupsInternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckMembership = channel.unary_unary(
                '/groups.GroupsInternal/CheckMembership',
                request_serializer=app_dot_grpc_dot_proto_dot_groups__pb2.CheckMembershipRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_proto_dot_groups__pb2.CheckMembershipResponse.FromString,
                _registered_method=True)
        self.CheckSharedGroup = channel.unary_unary(
                '/groups.GroupsInternal/CheckSharedGroup',
                request_serializer=app_dot_grpc_dot_proto_dot_groups__pb2.CheckSharedGroupRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_proto_dot_groups__pb2.CheckSharedGroupResponse.FromString,
                _registered_method=True)


class GroupsInternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckMembership(self, request, context):
        """Permite verificar si un usuario pertenece a un grupo o a un canal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSharedGroup(self, request, context):
        """Verifica si dos usuarios comparten algún grupo (para permitir 1 a 1)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupsInternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckMembership': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckMembership,
                    request_deserializer=app_dot_grpc_dot_proto_dot_groups__pb2.CheckMembershipRequest.FromString,
                    response_serializer=app_dot_grpc_dot_proto_dot_groups__pb2.CheckMembershipResponse.SerializeToString,
            ),
            'CheckSharedGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSharedGroup,
                    request_deserializer=app_dot_grpc_dot_proto_dot_groups__pb2.CheckSharedGroupRequest.FromString,
                    response_serializer=app_dot_grpc_dot_proto_dot_groups__pb2.CheckSharedGroupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groups.GroupsInternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groups.GroupsInternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupsInternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckMembership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groups.GroupsInternal/CheckMembership',
            app_dot_grpc_dot_proto_dot_groups__pb2.CheckMembershipRequest.SerializeToString,
            app_dot_grpc_dot_proto_dot_groups__pb2.CheckMembershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSharedGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groups.GroupsInternal/CheckSharedGroup',
            app_dot_grpc_dot_proto_dot_groups__pb2.CheckSharedGroupRequest.SerializeToString,
            app_dot_grpc_dot_proto_dot_groups__pb2.CheckSharedGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
