apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: messaging-attachments-pvc
  labels:
    app: groupsapp-messaging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: efs-sc
