apiVersion: v1
kind: Secret
metadata:
  name: messaging-secrets
  labels:
    app: groupsapp-messaging
type: Opaque
stringData:
  DATABASE_URL: postgresql+asyncpg://<rds_user>:<rds_password>@<rds_endpoint>:5432/groupsapp_messaging
  RABBITMQ_URL: amqp://<rabbitmq_user>:<rabbitmq_password>@<rabbitmq-service>:5672/
