apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: groupsapp-alb
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  subnets:
    ids:
      - subnet-0106505a4b096064e
      - subnet-00a0f8bd7d8a25be2
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: groupsapp-alb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: groupsapp-alb
  namespace: groupsapp
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: groupsapp-api-gateway
                port:
                  number: 80
