apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  labels:
    app: groupsapp-auth
type: Opaque
stringData:
  DATABASE_URL: postgresql+asyncpg://<rds_user>:<rds_password>@<rds_endpoint>:5432/groupsapp_auth
  JWT_SECRET_KEY: <replace-with-strong-random-secret>
  RABBITMQ_URL: amqp://<rabbitmq_user>:<rabbitmq_password>@<rabbitmq-service>:5672/
