apiVersion: v1
kind: Service
metadata:
  name: groupsapp-auth
  labels:
    app: groupsapp-auth
spec:
  selector:
    app: groupsapp-auth
  ports:
    - name: http
      port: 80
      targetPort: 8081
    - name: grpc
      port: 50052
      targetPort: 50052
  type: ClusterIP
