# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc.proto import auth_pb2 as app_dot_grpc_dot_proto_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/grpc/proto/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthInternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateToken = channel.unary_unary(
                '/auth.v1.AuthInternal/ValidateToken',
                request_serializer=app_dot_grpc_dot_proto_dot_auth__pb2.TokenValidationRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_proto_dot_auth__pb2.TokenValidationResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/auth.v1.AuthInternal/GetUser',
                request_serializer=app_dot_grpc_dot_proto_dot_auth__pb2.UserLookupRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_proto_dot_auth__pb2.UserProfile.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/auth.v1.AuthInternal/StreamEvents',
                request_serializer=app_dot_grpc_dot_proto_dot_auth__pb2.EventSubscriptionRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_proto_dot_auth__pb2.AuthEvent.FromString,
                _registered_method=True)


class AuthInternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthInternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=app_dot_grpc_dot_proto_dot_auth__pb2.TokenValidationRequest.FromString,
                    response_serializer=app_dot_grpc_dot_proto_dot_auth__pb2.TokenValidationResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=app_dot_grpc_dot_proto_dot_auth__pb2.UserLookupRequest.FromString,
                    response_serializer=app_dot_grpc_dot_proto_dot_auth__pb2.UserProfile.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=app_dot_grpc_dot_proto_dot_auth__pb2.EventSubscriptionRequest.FromString,
                    response_serializer=app_dot_grpc_dot_proto_dot_auth__pb2.AuthEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.v1.AuthInternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.v1.AuthInternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthInternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.AuthInternal/ValidateToken',
            app_dot_grpc_dot_proto_dot_auth__pb2.TokenValidationRequest.SerializeToString,
            app_dot_grpc_dot_proto_dot_auth__pb2.TokenValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.AuthInternal/GetUser',
            app_dot_grpc_dot_proto_dot_auth__pb2.UserLookupRequest.SerializeToString,
            app_dot_grpc_dot_proto_dot_auth__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/auth.v1.AuthInternal/StreamEvents',
            app_dot_grpc_dot_proto_dot_auth__pb2.EventSubscriptionRequest.SerializeToString,
            app_dot_grpc_dot_proto_dot_auth__pb2.AuthEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
