# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc/proto/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/grpc/proto/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pp/grpc/proto/auth.proto\x12\x07\x61uth.v1\".\n\x16TokenValidationRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"u\n\x17TokenValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x1b\n\x13\x65xpires_at_epoch_ms\x18\x05 \x01(\x03\"$\n\x11UserLookupRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\xb5\x01\n\x0bUserProfile\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x1b\n\x13\x63reated_at_epoch_ms\x18\x06 \x01(\x03\x12\x1e\n\x16last_login_at_epoch_ms\x18\x07 \x01(\x03\x12\x11\n\tis_online\x18\x08 \x01(\x08\"D\n\x18\x45ventSubscriptionRequest\x12\x13\n\x0b\x63onsumer_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65vent_types\x18\x02 \x03(\t\"\x88\x01\n\tAuthEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x14\n\x0csubject_type\x18\x03 \x01(\t\x12\x12\n\nsubject_id\x18\x04 \x01(\t\x12\x14\n\x0cpayload_json\x18\x05 \x01(\t\x12\x1b\n\x13\x63reated_at_epoch_ms\x18\x06 \x01(\x03\x32\xe8\x01\n\x0c\x41uthInternal\x12R\n\rValidateToken\x12\x1f.auth.v1.TokenValidationRequest\x1a .auth.v1.TokenValidationResponse\x12;\n\x07GetUser\x12\x1a.auth.v1.UserLookupRequest\x1a\x14.auth.v1.UserProfile\x12G\n\x0cStreamEvents\x12!.auth.v1.EventSubscriptionRequest\x1a\x12.auth.v1.AuthEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc.proto.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENVALIDATIONREQUEST']._serialized_start=38
  _globals['_TOKENVALIDATIONREQUEST']._serialized_end=84
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_start=86
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_end=203
  _globals['_USERLOOKUPREQUEST']._serialized_start=205
  _globals['_USERLOOKUPREQUEST']._serialized_end=241
  _globals['_USERPROFILE']._serialized_start=244
  _globals['_USERPROFILE']._serialized_end=425
  _globals['_EVENTSUBSCRIPTIONREQUEST']._serialized_start=427
  _globals['_EVENTSUBSCRIPTIONREQUEST']._serialized_end=495
  _globals['_AUTHEVENT']._serialized_start=498
  _globals['_AUTHEVENT']._serialized_end=634
  _globals['_AUTHINTERNAL']._serialized_start=637
  _globals['_AUTHINTERNAL']._serialized_end=869
# @@protoc_insertion_point(module_scope)
